-- create user 
CREATE USER PREGUNTADOS
	IDENTIFIED BY preguntados
	DEFAULT TABLESPACE USERS
	TEMPORARY TABLESPACE TEMP
	PROFILE DEFAULT;


-- grant/revoke role privilages
GRANT RESOURCE TO PREGUNTADOS;
GRANT CONNECT TO PREGUNTADOS;
GRANT DBA TO PREGUNTADOS;
-- grant/revoke system privilages
GRANT CREATE SESSION TO PREGUNTADOS;
GRANT UNLIMITED TABLESPACE TO PREGUNTADOS;